package sistemadegestao.servidorOperacoes.services;


/**
* sistemadegestao.servidorOperacoes.services/_ImprimirDadosStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Monday, September 25, 2023 12:21:25 AM CAT
*/

public class _ImprimirDadosStub extends org.omg.CORBA.portable.ObjectImpl implements sistemadegestao.servidorOperacoes.services.ImprimirDados
{

  public void getConsultas (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getConsultas", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getConsultas (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getConsultas

  public void getCirurgias (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCirurgias", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getCirurgias (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getCirurgias

  public void getPacientes (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPacientes", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getPacientes (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getPacientes

  public void getMedicosConsulta (String tipo, org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMedicosConsulta", true);
                $out.write_string (tipo);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMedicosConsulta (tipo, lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getMedicosConsulta

  public void getMedicos (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMedicos", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMedicos (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getMedicos

  public void VerAgendaMedico (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("VerAgendaMedico", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                VerAgendaMedico (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // VerAgendaMedico

  public void getEnfComPac (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getEnfComPac", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getEnfComPac (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getEnfComPac

  public void getEnfermeiros (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getEnfermeiros", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getEnfermeiros (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // getEnfermeiros

  public void verPacEnf (org.omg.CORBA.Any[] lista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("verPacEnf", true);
                sistemadegestao.servidorOperacoes.services.ListaHelper.write ($out, lista);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                verPacEnf (lista        );
            } finally {
                _releaseReply ($in);
            }
  } // verPacEnf

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sistemadegestao.servidorOperacoes.services/ImprimirDados:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ImprimirDadosStub
