package sistemadegestao.servidorOperacoes.services;


/**
* services/DadosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Monday, September 25, 2023 12:21:25 AM CAT
*/

public abstract class DadosPOA extends org.omg.PortableServer.Servant
 implements sistemadegestao.servidorOperacoes.services.DadosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("agendarCirurgia", new java.lang.Integer (0));
    _methods.put ("agendarConsulta", new java.lang.Integer (1));
    _methods.put ("cancelar", new java.lang.Integer (2));
    _methods.put ("darAltaPaciente", new java.lang.Integer (3));
    _methods.put ("internarPaciente", new java.lang.Integer (4));
    _methods.put ("registarPaciente", new java.lang.Integer (5));
    _methods.put ("registarEnf", new java.lang.Integer (6));
    _methods.put ("registarMed", new java.lang.Integer (7));
    _methods.put ("getdados", new java.lang.Integer (8));
    _methods.put ("lerDados", new java.lang.Integer (9));
    _methods.put ("gravarDados", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // services/Dados/agendarCirurgia
       {
         this.agendarCirurgia ();
         out = $rh.createReply();
         break;
       }

       case 1:  // services/Dados/agendarConsulta
       {
         this.agendarConsulta ();
         out = $rh.createReply();
         break;
       }

       case 2:  // services/Dados/cancelar
       {
         String tipo = in.read_string ();
         this.cancelar (tipo);
         out = $rh.createReply();
         break;
       }

       case 3:  // services/Dados/darAltaPaciente
       {
         this.darAltaPaciente ();
         out = $rh.createReply();
         break;
       }

       case 4:  // services/Dados/internarPaciente
       {
         this.internarPaciente ();
         out = $rh.createReply();
         break;
       }

       case 5:  // services/Dados/registarPaciente
       {
         this.registarPaciente ();
         out = $rh.createReply();
         break;
       }

       case 6:  // services/Dados/registarEnf
       {
         this.registarEnf ();
         out = $rh.createReply();
         break;
       }

       case 7:  // services/Dados/registarMed
       {
         this.registarMed ();
         out = $rh.createReply();
         break;
       }

       case 8:  // services/Dados/getdados
       {
         org.omg.CORBA.Any $result[] = null;
         $result = this.getdados ();
         out = $rh.createReply();
         sistemadegestao.servidorOperacoes.services.ListaHelper.write (out, $result);
         break;
       }

       case 9:  // services/Dados/lerDados
       {
         this.lerDados ();
         out = $rh.createReply();
         break;
       }

       case 10:  // services/Dados/gravarDados
       {
         this.gravarDados ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:services/Dados:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dados _this() 
  {
    return DadosHelper.narrow(
    super._this_object());
  }

  public Dados _this(org.omg.CORBA.ORB orb) 
  {
    return DadosHelper.narrow(
    super._this_object(orb));
  }


} // class DadosPOA
