package sistemadegestao.servidorOperacoes.services;


/**
* services/DadosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Tuesday, September 26, 2023 12:11:44 PM CAT
*/

public interface DadosOperations 
{
  void agendarCirurgia ();
  void agendarConsulta ();
  void cancelar (String tipo);
  void darAltaPaciente ();
  void internarPaciente ();
  void registarPaciente ();
  void registarEnf ();
  void registarMed ();
  void lerDados ();
  void gravarDados ();
} // interface DadosOperations
