package sistemadegestao.servidorOperacoes.services;


/**
* services/ImprimirDados.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Monday, September 25, 2023 12:21:25 AM CAT
*/

public interface ImprimirDados extends ImprimirDadosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ImprimirDados
