package sistemadegestao.servidorOperacoes.services;


/**
* services/ImprimirDadosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Monday, September 25, 2023 12:21:25 AM CAT
*/

public abstract class ImprimirDadosPOA extends org.omg.PortableServer.Servant
 implements sistemadegestao.servidorOperacoes.services.ImprimirDadosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getConsultas", new java.lang.Integer (0));
    _methods.put ("getCirurgias", new java.lang.Integer (1));
    _methods.put ("getPacientes", new java.lang.Integer (2));
    _methods.put ("getMedicosConsulta", new java.lang.Integer (3));
    _methods.put ("getMedicos", new java.lang.Integer (4));
    _methods.put ("VerAgendaMedico", new java.lang.Integer (5));
    _methods.put ("getEnfComPac", new java.lang.Integer (6));
    _methods.put ("getEnfermeiros", new java.lang.Integer (7));
    _methods.put ("verPacEnf", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sistemadegestao.servidorOperacoes.services/ImprimirDados/getConsultas
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getConsultas (lista);
         out = $rh.createReply();
         break;
       }

       case 1:  // services/ImprimirDados/getCirurgias
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getCirurgias (lista);
         out = $rh.createReply();
         break;
       }

       case 2:  // services/ImprimirDados/getPacientes
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getPacientes (lista);
         out = $rh.createReply();
         break;
       }

       case 3:  // services/ImprimirDados/getMedicosConsulta
       {
         String tipo = in.read_string ();
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getMedicosConsulta (tipo, lista);
         out = $rh.createReply();
         break;
       }

       case 4:  // services/ImprimirDados/getMedicos
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getMedicos (lista);
         out = $rh.createReply();
         break;
       }

       case 5:  // services/ImprimirDados/VerAgendaMedico
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.VerAgendaMedico (lista);
         out = $rh.createReply();
         break;
       }

       case 6:  // services/ImprimirDados/getEnfComPac
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getEnfComPac (lista);
         out = $rh.createReply();
         break;
       }

       case 7:  // services/ImprimirDados/getEnfermeiros
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.getEnfermeiros (lista);
         out = $rh.createReply();
         break;
       }

       case 8:  // services/ImprimirDados/verPacEnf
       {
         org.omg.CORBA.Any lista[] = sistemadegestao.servidorOperacoes.services.ListaHelper.read (in);
         this.verPacEnf (lista);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:services/ImprimirDados:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ImprimirDados _this() 
  {
    return ImprimirDadosHelper.narrow(
    super._this_object());
  }

  public ImprimirDados _this(org.omg.CORBA.ORB orb) 
  {
    return ImprimirDadosHelper.narrow(
    super._this_object(orb));
  }


} // class ImprimirDadosPOA
