package sistemadegestao.servidorOperacoes.services;


/**
* services/ImpressoesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Tuesday, September 26, 2023 12:11:44 PM CAT
*/

public abstract class ImpressoesPOA extends org.omg.PortableServer.Servant
 implements sistemadegestao.servidorOperacoes.services.ImpressoesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ImprimirCons", new java.lang.Integer (0));
    _methods.put ("ImprimirCir", new java.lang.Integer (1));
    _methods.put ("getPacientes", new java.lang.Integer (2));
    _methods.put ("ImprimirMedico", new java.lang.Integer (3));
    _methods.put ("ImprimirAllMed", new java.lang.Integer (4));
    _methods.put ("agenda", new java.lang.Integer (5));
    _methods.put ("EnfComPacientes", new java.lang.Integer (6));
    _methods.put ("ImprimirEnf", new java.lang.Integer (7));
    _methods.put ("verPacientesEnf", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // services/Impressoes/ImprimirCons
       {
         this.ImprimirCons ();
         out = $rh.createReply();
         break;
       }

       case 1:  // services/Impressoes/ImprimirCir
       {
         this.ImprimirCir ();
         out = $rh.createReply();
         break;
       }

       case 2:  // services/Impressoes/getPacientes
       {
         this.getPacientes ();
         out = $rh.createReply();
         break;
       }

       case 3:  // services/Impressoes/ImprimirMedico
       {
         String tipo = in.read_string ();
         this.ImprimirMedico (tipo);
         out = $rh.createReply();
         break;
       }

       case 4:  // services/Impressoes/ImprimirAllMed
       {
         this.ImprimirAllMed ();
         out = $rh.createReply();
         break;
       }

       case 5:  // services/Impressoes/agenda
       {
         this.agenda ();
         out = $rh.createReply();
         break;
       }

       case 6:  // services/Impressoes/EnfComPacientes
       {
         this.EnfComPacientes ();
         out = $rh.createReply();
         break;
       }

       case 7:  // services/Impressoes/ImprimirEnf
       {
         this.ImprimirEnf ();
         out = $rh.createReply();
         break;
       }

       case 8:  // services/Impressoes/verPacientesEnf
       {
         this.verPacientesEnf ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:services/Impressoes:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Impressoes _this() 
  {
    return ImpressoesHelper.narrow(
    super._this_object());
  }

  public Impressoes _this(org.omg.CORBA.ORB orb) 
  {
    return ImpressoesHelper.narrow(
    super._this_object(orb));
  }


} // class ImpressoesPOA
