package sistemadegestao.servidorOperacoes.services;


/**
* services/ImpressoesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Tuesday, September 26, 2023 12:11:44 PM CAT
*/

public interface ImpressoesOperations 
{
  void ImprimirCons ();
  void ImprimirCir ();
  void getPacientes ();
  void ImprimirMedico (String tipo);
  void ImprimirAllMed ();
  void agenda ();
  void EnfComPacientes ();
  void ImprimirEnf ();
  void verPacientesEnf ();
} // interface ImpressoesOperations
