package sistemadegestao.servidorOperacoes.services;


/**
* services/ImprimirDadosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Monday, September 25, 2023 12:21:25 AM CAT
*/

public interface ImprimirDadosOperations 
{
  void getConsultas (org.omg.CORBA.Any[] lista);
  void getCirurgias (org.omg.CORBA.Any[] lista);
  void getPacientes (org.omg.CORBA.Any[] lista);
  void getMedicosConsulta (String tipo, org.omg.CORBA.Any[] lista);
  void getMedicos (org.omg.CORBA.Any[] lista);
  void VerAgendaMedico (org.omg.CORBA.Any[] lista);
  void getEnfComPac (org.omg.CORBA.Any[] lista);
  void getEnfermeiros (org.omg.CORBA.Any[] lista);
  void verPacEnf (org.omg.CORBA.Any[] lista);
} // interface ImprimirDadosOperations
