package sistemadegestao.servidorOperacoes.services;


/**
* services/Impressoes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Tuesday, September 26, 2023 12:11:44 PM CAT
*/

public interface Impressoes extends ImpressoesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Impressoes
