package sistemadegestao.servidorOperacoes.services;

/**
* sistemadegestao.servidorOperacoes.sistemadegestao.servidorOperacoes.services/ImprimirDadosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Monday, September 25, 2023 12:21:25 AM CAT
*/

public final class ImprimirDadosHolder implements org.omg.CORBA.portable.Streamable
{
  public sistemadegestao.servidorOperacoes.services.ImprimirDados value = null;

  public ImprimirDadosHolder ()
  {
  }

  public ImprimirDadosHolder (sistemadegestao.servidorOperacoes.services.ImprimirDados initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sistemadegestao.servidorOperacoes.services.ImprimirDadosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sistemadegestao.servidorOperacoes.services.ImprimirDadosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sistemadegestao.servidorOperacoes.services.ImprimirDadosHelper.type ();
  }

}
