package sistemadegestao.servidorOperacoes.services;

/**
* services/ImpressoesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clinica.idl
* Tuesday, September 26, 2023 12:11:44 PM CAT
*/

public final class ImpressoesHolder implements org.omg.CORBA.portable.Streamable
{
  public sistemadegestao.servidorOperacoes.services.Impressoes value = null;

  public ImpressoesHolder ()
  {
  }

  public ImpressoesHolder (sistemadegestao.servidorOperacoes.services.Impressoes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sistemadegestao.servidorOperacoes.services.ImpressoesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        sistemadegestao.servidorOperacoes.services.ImpressoesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sistemadegestao.servidorOperacoes.services.ImpressoesHelper.type ();
  }

}
