package sistemadegestao.servidorValidacao;


/**
* validacao/ArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Tuesday, September 26, 2023 11:20:06 AM CAT
*/

public final class ArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ArrayHolder ()
  {
  }

  public ArrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sistemadegestao.servidorValidacao.ArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        sistemadegestao.servidorValidacao.ArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sistemadegestao.servidorValidacao.ArrayHelper.type ();
  }

}
