package sistemadegestao.servidorValidacao;


/**
* validacao/SequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Sunday, September 24, 2023 8:14:11 PM CAT
*/

public final class SequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public SequenceHolder ()
  {
  }

  public SequenceHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sistemadegestao.servidorValidacao.SequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        sistemadegestao.servidorValidacao.SequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sistemadegestao.servidorValidacao.SequenceHelper.type ();
  }

}
