package sistemadegestao.servidorValidacao.App.Validacao;

/**
* validacao/ValidacaoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Tuesday, September 26, 2023 11:20:06 AM CAT
*/

public final class ValidacaoHolder implements org.omg.CORBA.portable.Streamable
{
  public sistemadegestao.servidorValidacao.App.Validacao.Validacao value = null;

  public ValidacaoHolder ()
  {
  }

  public ValidacaoHolder (sistemadegestao.servidorValidacao.App.Validacao.Validacao initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sistemadegestao.servidorValidacao.App.Validacao.ValidacaoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sistemadegestao.servidorValidacao.App.Validacao.ValidacaoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sistemadegestao.servidorValidacao.App.Validacao.ValidacaoHelper.type ();
  }

}
