package sistemadegestao.servidorValidacao.App.Validacao;

import java.io.IOException;


/**
* validacao/ValidacaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Tuesday, September 26, 2023 11:20:06 AM CAT
*/

public interface ValidacaoOperations 
{
  byte validarByte (byte a, byte b, String s) throws IOException;
  String validarString (int a, int b, String s) throws IOException;
  int validarInt (int a, int b, String s) throws IOException;
  char validarChar (char a, char b, String c) throws IOException;
  String validarData () throws IOException;
  String validarHora () throws IOException;
  String[] validarTelefone () throws IOException;
  void mensagem (String text) throws IOException;
} // interface ValidacaoOperations
