package sistemadegestao.servidorValidacao.App.Validacao;


/**
* validacao/Validacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Tuesday, September 26, 2023 11:20:06 AM CAT
*/

public interface Validacao extends ValidacaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Validacao
