package sistemadegestao.servidorValidacao.Server.validacao;


/**
* validacao/Validacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Sunday, September 24, 2023 10:23:13 PM CAT
*/

public interface Validacao extends ValidacaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Validacao
