package sistemadegestao.servidorValidacao.Server.validacao;

import java.io.IOException;


/**
* validacao/ValidacaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Sunday, September 24, 2023 10:23:13 PM CAT
*/

public interface ValidacaoOperations 
{
  byte validarByte (byte a, byte b, String s) throws IOException;
  String validarString (int a, int b, String s)throws IOException;
  int validarInt (int a, int b, String s)throws IOException;
  char validarChar (char a, char b, String c) throws IOException;
  String validarData () throws IOException;
  String validarHora () throws IOException;
  String[] validarTelefone () throws IOException;
} // interface ValidacaoOperations
