package sistemadegestao.servidorValidacao.Server.validacao;

/**
* validacao/ValidacaoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Validacao.idl
* Sunday, September 24, 2023 10:23:13 PM CAT
*/

public final class ValidacaoHolder implements org.omg.CORBA.portable.Streamable
{
  public sistemadegestao.servidorValidacao.Server.validacao.Validacao value = null;

  public ValidacaoHolder ()
  {
  }

  public ValidacaoHolder (sistemadegestao.servidorValidacao.Server.validacao.Validacao initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sistemadegestao.servidorValidacao.Server.validacao.ValidacaoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        sistemadegestao.servidorValidacao.Server.validacao.ValidacaoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sistemadegestao.servidorValidacao.Server.validacao.ValidacaoHelper.type ();
  }

}
