package sistemadegestao.servidorValidacao.App.Output;


/**
* Output.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Output.idl
* Monday, September 25, 2023 11:56:00 AM CAT
*/

public interface Output extends OutputOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Output
