package sistemadegestao.servidorValidacao.App.Output;


/**
* OutputHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Output.idl
* Monday, September 25, 2023 11:56:00 AM CAT
*/

abstract public class OutputHelper
{
  private static String  _id = "IDL:Output:1.0";

  public static void insert (org.omg.CORBA.Any a, Output that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Output extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OutputHelper.id (), "Output");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Output read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OutputStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Output value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Output narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Output)
      return (Output)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _OutputStub stub = new _OutputStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Output unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Output)
      return (Output)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _OutputStub stub = new _OutputStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
