package sistemadegestao.servidorValidacao.App.Output;


/**
* OutputHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Output.idl
* Monday, September 25, 2023 11:56:00 AM CAT
*/

public final class OutputHolder implements org.omg.CORBA.portable.Streamable
{
  public Output value = null;

  public OutputHolder ()
  {
  }

  public OutputHolder (Output initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OutputHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OutputHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OutputHelper.type ();
  }

}
